const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
  EMAIL_PASSWORD_SUCCESS: "EMAIL_PASSWORD_SUCCESS",
  EMAIL_PASSWORD_ERROR: "EMAIL_PASSWORD_ERROR",
  RESET_AUTH_FORMS: "RESET_AUTH_FORMS",
};

export default userTypes;
