const userTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_UP_START: "SIGN_UP_START",
  RETRIEVE_PASSWORD_START: " RETRIEVE_PASSWORD_START",
  RETRIEVE_PASSWORD_SUCCESS: "RETRIEVE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_START: " UPDATE_PASSWORD_START",
  UPDATE_PASSWORD_SUCCESS: " UPDATE_PASSWORD_SUCCESS",
  USER_ERROR: "USER_ERROR",
  RESET_USER_STATE: "RESET_USER_STATE",
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  ADD_USERS_START: "ADD_USERS_START",
};

export default userTypes;
