const productTypes = {
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  ADD_PRODUCT_START: "ADD_PRODUCT_START",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",

  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  ADD_CATEGORY_START: "ADD_CATEGORY_START",
  DELETE_CATEGORY_START: "DELETE_CATEGORY_START",

  PRODUCT_ERROR: "PRODUCT_ERROR",
};

export default productTypes;
